### PR TITLE
Set up VCR for API test fixtures

### PR DESCRIPTION
**Pull request by pengwynn**
_WIP_: 

This branch
- Adds VCR for recording API test fixtures
- Adds the usual `script/*` suspects

I'm not sure yet which balance we should strike for what we mock purely with Webmock, what we stub on Octokit, and what we record, but I wanted to get VCR into the project before we get too.

/cc @cored

### CODE REVIEW

**Comment by cored** [comment]
I think probably we should just hit the API directly with VCR in place and part from there, independent of what octonaut is mocking at the moment, thoughts?

**Comment by pengwynn** [comment]
I think that should be the preferred approach, but some calls (Git Data API and others) require a lot of dependent chunks of data to be in place to make a particular call. Since our goal isn't to test Octokit, we should make some tradeoffs and either use Webmock or stub Octokit in those cases.

**Comment by cored** [comment]
Why not go all the way and mock octokit. It's been already tested in its
own project.

**Comment by pengwynn** [comment]
In many cases VCR is the least amount of work. Make a call, get a cassette. You don't have to spend a lot of time constructing a mock response.

**Pull request closed without merging**
